version: 2.1
setup: true
orbs:
    continuation: circleci/continuation@0.1.0

parameters:
    nightly:
        type: boolean
        default: false

jobs:
    check_code_quality:
        working_directory: ~/transformers
        docker:
            - image: cimg/python:3.8.12
        resource_class: large
        environment:
            TRANSFORMERS_IS_CI: yes
            PYTEST_TIMEOUT: 120
        parallelism: 1
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v0.6-code_quality-{{ checksum "setup.py" }}
                      - v0.6-code-quality
            - restore_cache:
                  keys:
                      - v0.6-code_quality-{{ checksum "setup.py" }}-site-packages
                      - v0.6-code-quality-site-packages
            - run: pip install --upgrade pip
            - run: pip install -U .[all,quality]
            - save_cache:
                  key: v0.6-code_quality-{{ checksum "setup.py" }}
                  paths:
                      - '~/.cache/pip'
            - save_cache:
                  key: v0.6-code_quality-{{ checksum "setup.py" }}-site-packages
                  paths:
                      - '~/.pyenv/versions/'
            - run:
                name: Show installed libraries and their versions
                command: pip freeze | tee installed.txt
            - store_artifacts:
                  path: ~/transformers/installed.txt
            - run: black --check examples tests src utils
            - run: ruff examples tests src utils
            - run: python utils/custom_init_isort.py --check_only
            - run: python utils/sort_auto_mappings.py --check_only
            - run: doc-builder style src/transformers docs/source --max_len 119 --check_only --path_to_docs docs/source
            - run: python utils/check_doc_toc.py --fix_and_overwrite
            - store_artifacts:
                  path: ~/transformers/docs/source/en/_toctree.yml

workflows:
    version: 2
    setup_and_quality:
        when:
            not: <<pipeline.parameters.nightly>>
        jobs:
            - check_code_quality
